### ISSUE TITLE
Django框架和Semantic-UI框架的基本部署

### ISSUE THREAD

**Issue by Fihezro** [bugphobia/XuebaOnline#1]
**框架部署**
- Django
- Semantic-UI

**Comment by fzyz999** [comment]
修补了一下Semantic-UI的图标不显示的问题，已完成。

**Comment by wwjwhen** [comment]
回复 [@王鹿鸣](https://team.oschina.net/Bugphobia/u/915667) :赞鸣神~:smiley:
