### ISSUE TITLE
完成搜索结果页面的代码迁移工作

### ISSUE THREAD

**Issue by PocketPanacea** [bugphobia/XuebaOnline#35]
- 完成搜索结果页的代码迁移工作：
  - 不再链接到原URL，尝试将问答对直接展示在我们的页面中。
  - 无法搜索到结果时一定要返回一个未搜到相关内容的页面，而非“空”
  - 对Like、Ask、Upload等功能按钮进行完善
  - 搜索结果分页处理，而非大量内容直接直接铺陈开来（用户能够规定每页的显示数目）
  - 对用户上传资源的文件名等进行搜索（类似百度文库，在此任务中完成静态页面）
- 特别说明：各分部任务的截止时间将以子任务的形式给出

**Comment by JuruoMP** [comment]
迁移代码已经完成，但是由于环境问题尚无法测试是否正确

**Comment by PocketPanacea** [comment]
搜索结果页面的迁移工作正常完成，但由于环境配置等问题难以进行测试，因此在关闭此任务的同时发布“搜索结果页面”的代码复审工作，检查基本前端功能是否实现

**Comment by PocketPanacea** [comment]
搜索结果页面的迁移工作正常完成，但由于环境配置等问题难以进行测试，因此在关闭此任务的同时发布“搜索结果页面”的代码复审工作，检查基本前端功能是否实现
