### ISSUE TITLE
用户管理的Read Later功能

### ISSUE THREAD

**Issue by PocketPanacea** [bugphobia/XuebaOnline#37]
“Read Later”功能，就相当于收藏、喜欢、关注，同时做一个推荐
    - 针对接口需求封装Json数据，并实现接口
    - 需要对标签、对问答、对课程都设置相关操作
    - 由于我们的系统用户基础数据不多，所以相当于“冷启动”，所以我们的数据分析不是建立在用户上，而是建立在内容上的相关性
    - 根据用户的收藏和喜好，将相应的推荐内容找出来

**Comment by Fihezro** [comment]
已经完成关于问答的数据库model，以及一些交互的接口views。
