### ISSUE TITLE
完成搜索管理并实现即时结果信息的反馈

### ISSUE THREAD

**Issue by PocketPanacea** [bugphobia/XuebaOnline#40]
搜索管理：实现搜索结果信息的反馈（！）
    - 将结果封装成接口对接数据
    - 做好分类，因为问答数据、课程数据（站内和站外数据也会产生区别）等等都是来自不同的地方用不同的结构存储的，最好分别实现操作
    - 严格区分网站内实现的提问和网站外爬取的提问

**Comment by wwjwhen** [comment]
首先是截止时间的事情，截止时间就设到最晚这周五吧，我尽量看看周四能不能把他搞定。（这个过程中需要鸣神和小冯的密切配合，因为最初的model的属性集合是鸣神定义的，搜索功能的实现也是小冯做的，我要整合这两部分的内容势必需要他们的助攻（在时间这么紧张的前提下））

**Comment by wwjwhen** [comment]
搜索结果后端的基本思路的说明：需要注意的是在question以及answer的两个类中有若干的相关的属性，要是想要做到区分问题的来源和问题的作用域，需要在这两个类的属性域上分别加上source以及destination这两个属性，通过这两个属性可以初步实现问题的分类，暂时的思路是这样的。

**Comment by wwjwhen** [comment]
将结果封装成接口对接数据这里想要简单地使用json格式进行数据的封装，也利于数据的直接利用和处理。
