### ISSUE TITLE
主页面后端开发

### ISSUE THREAD

**Issue by JuruoMP** [bugphobia/XuebaOnline#5]
根据界面设计开发相应功能

**Comment by Fihezro** [comment]
将用户管理和搜索都搁置后，还有什么属于后端啊？

**Comment by JuruoMP** [comment]
回复 [@Fihezro](https://team.oschina.net/Bugphobia/u/1440900) ：学爷那边Slor接口没出来，所以基本上就是一些跳转。可以趁现在赶紧把网站结构做出来

**Comment by Fihezro** [comment]
基于首页的后端链接设计已完成
